spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  h2.console:
    enabled: true
    path: /h2-console
  datasource:
    url: jdbc:h2:mem:test;Mode=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    continue-on-error: false
    initialization-mode: always