INSERT INTO "USER" (ID, USERNAME, PASSWORD, BLOCKED)
VALUES (1, 'Stuart', 'Password', 0 );




INSERT INTO "AUTHORITY" (ID, AUTHORITY, USER_ID)
VALUES (100, 'ADMIN', 1 );


INSERT INTO "AUTHORITY" (ID, AUTHORITY, USER_ID)
VALUES (101, 'USER', 1 );
